name: Docker Deployment
author: Al-waleed Shihadeh <wshihadeh.dev@gmail.com>
description: A GitHub Action that supports docker-compose and Docker Swarm deployments
inputs:
  remote_docker_host:
    description: Remote Docker host ie (user@host)
    required: true
  ssh_public_key:
    description: Remote Docker SSH public key
    required: true
  ssh_private_key:
    description: SSH private key used to connect to the docker host
    required: true
  args:
    description: Deployment command args.
    required: true
  deploy_path:
    description: The path where the stack files will be copied to. Default ~/docker-deployment.
    required: false
  stack_file_name:
    description: Docker stack file used. Default is docker-compose.yaml
    required: false
  env_file_name:
    description: Enironment file to be copied. Default is .env
    required: false
  keep_files:
    description: Number of the files to be kept on the server. Default is 3.
    required: false
  docker_prune:
    description: A boolean input to trigger docker prune command.
    required: false
  pull_images_first:
    description: Pull docker images before deploying.
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: send
  color: green

